apiVersion: v1
kind: Service
metadata:
  name: starbucks
  labels:
    app: starbucks
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: starbucks
